# Generated by Django 2.2.16 on 2022-02-28 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220228_0011'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='title',
            name='year_lte_now',
        ),
    ]
